import requests
import json
from datetime import datetime, timezone

def send_to_discord(paper, summary, webhook_url):
    """
    Sends the paper information and summary to Discord via Webhook.
    """
    if not webhook_url:
        print("❌ Error: Webhook URL is missing.")
        return

    # Ensure summary is a string (handle None cases)
    if summary is None:
        summary = "No summary available."

    # Create Embed structure
    embed = {
        "title": paper.get('title', 'No Title'),
        "url": paper.get('url', ''),
        "description": summary if len(summary) < 4096 else summary[:4090] + "...",
        "color": 3447003,  # Blue color
        "fields": [
            {
                "name": "Journal / Source",
                "value": paper.get('journal', 'Unknown'),
                "inline": True
            },
            {
                "name": "Date",
                "value": paper.get('date', 'Unknown'),
                "inline": True
            },
        ],
        "footer": {
            "text": "Paper Digest Bot • Generated by Gemini"
        },
        # Use timezone-aware datetime (Recommended for Python 3.12+)
        "timestamp": datetime.now(timezone.utc).isoformat()
    }

    payload = {
        "username": "Paper Digest Bot",
        "embeds": [embed]
    }

    try:
        response = requests.post(
            webhook_url, 
            data=json.dumps(payload), 
            headers={"Content-Type": "application/json"}
        )
        if response.status_code == 204:
            print("✅ Successfully sent to Discord.")
        else:
            print(f"❌ Failed to send to Discord. Status Code: {response.status_code}")
            print(f"Response: {response.text}") # Debug info
            
    except Exception as e:
        print(f"❌ Error sending webhook: {e}")